version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: ott-postgres-dev
    environment:
      POSTGRES_DB: ottdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ott-redis-dev
    ports:
      - "6379:6379"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ott-dynamodb-dev
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-dev-data:/home/dynamodblocal/data

volumes:
  postgres-dev-data:
  dynamodb-dev-data:
