spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zoladb_dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

aws:
  dynamodb:
    endpoint: http://localhost:8000

logging:
  level:
    com.zola: DEBUG
    org.springframework.web: DEBUG
