spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ottdb
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

aws:
  dynamodb:
    endpoint: http://localhost:8000

logging:
  level:
    com.ott: DEBUG
    org.springframework.web: DEBUG
