spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ottdb
    username: postgres
    password: admin

  flyway:
    enabled: false

  dynamodb:
    endpoint: http://localhost:8000

logging:
  level:
    com.ott: DEBUG
    org.springframework.web: DEBUG
